var searchData=
[
  ['cleandata_1360',['cleanData',['../namespaceepidemiology_1_1epidata_1_1cleanData.html',1,'epidemiology::epidata']]],
  ['commuter_5fmigration_5fbfa_1361',['commuter_migration_bfa',['../namespaceepidemiology_1_1epidata_1_1commuter__migration__bfa.html',1,'epidemiology::epidata']]],
  ['de_1362',['de',['../namespaceepi_1_1regions_1_1de.html',1,'epi::regions']]],
  ['defaultdict_1363',['defaultDict',['../namespaceepidemiology_1_1epidata_1_1defaultDict.html',1,'epidemiology::epidata']]],
  ['detail_1364',['detail',['../namespaceepi_1_1detail.html',1,'epi']]],
  ['details_1365',['details',['../namespaceepi_1_1details.html',1,'epi']]],
  ['epi_1366',['epi',['../namespaceepi.html',1,'']]],
  ['epidata_1367',['epidata',['../namespaceepidemiology_1_1epidata.html',1,'epidemiology']]],
  ['epidemiology_1368',['epidemiology',['../namespaceepidemiology.html',1,'']]],
  ['getdataintopandasdataframe_1369',['getDataIntoPandasDataFrame',['../namespaceepidemiology_1_1epidata_1_1getDataIntoPandasDataFrame.html',1,'epidemiology::epidata']]],
  ['getdividata_1370',['getDIVIData',['../namespaceepidemiology_1_1epidata_1_1getDIVIData.html',1,'epidemiology::epidata']]],
  ['getjhdata_1371',['getJHData',['../namespaceepidemiology_1_1epidata_1_1getJHData.html',1,'epidemiology::epidata']]],
  ['getpopulationdata_1372',['getPopulationData',['../namespaceepidemiology_1_1epidata_1_1getPopulationData.html',1,'epidemiology::epidata']]],
  ['getrkidata_1373',['getRKIData',['../namespaceepidemiology_1_1epidata_1_1getRKIData.html',1,'epidemiology::epidata']]],
  ['getrkidatawithestimations_1374',['getRKIDatawithEstimations',['../namespaceepidemiology_1_1epidata_1_1getRKIDatawithEstimations.html',1,'epidemiology::epidata']]],
  ['getsimulationdata_1375',['getSimulationData',['../namespaceepidemiology_1_1epidata_1_1getSimulationData.html',1,'epidemiology::epidata']]],
  ['getvaccinedata_1376',['getVaccineData',['../namespaceepidemiology_1_1epidata_1_1getVaccineData.html',1,'epidemiology::epidata']]],
  ['regions_1377',['regions',['../namespaceepi_1_1regions.html',1,'epi']]]
];
