var searchData=
[
  ['cleandata_1331',['cleanData',['../namespaceepidemiology_1_1epidata_1_1cleanData.html',1,'epidemiology::epidata']]],
  ['commuter_5fmigration_5fbfa_1332',['commuter_migration_bfa',['../namespaceepidemiology_1_1epidata_1_1commuter__migration__bfa.html',1,'epidemiology::epidata']]],
  ['de_1333',['de',['../namespaceepi_1_1regions_1_1de.html',1,'epi::regions']]],
  ['defaultdict_1334',['defaultDict',['../namespaceepidemiology_1_1epidata_1_1defaultDict.html',1,'epidemiology::epidata']]],
  ['detail_1335',['detail',['../namespaceepi_1_1detail.html',1,'epi']]],
  ['details_1336',['details',['../namespaceepi_1_1details.html',1,'epi']]],
  ['epi_1337',['epi',['../namespaceepi.html',1,'']]],
  ['epidata_1338',['epidata',['../namespaceepidemiology_1_1epidata.html',1,'epidemiology']]],
  ['epidemiology_1339',['epidemiology',['../namespaceepidemiology.html',1,'']]],
  ['getdataintopandasdataframe_1340',['getDataIntoPandasDataFrame',['../namespaceepidemiology_1_1epidata_1_1getDataIntoPandasDataFrame.html',1,'epidemiology::epidata']]],
  ['getdividata_1341',['getDIVIData',['../namespaceepidemiology_1_1epidata_1_1getDIVIData.html',1,'epidemiology::epidata']]],
  ['getjhdata_1342',['getJHData',['../namespaceepidemiology_1_1epidata_1_1getJHData.html',1,'epidemiology::epidata']]],
  ['getpopulationdata_1343',['getPopulationData',['../namespaceepidemiology_1_1epidata_1_1getPopulationData.html',1,'epidemiology::epidata']]],
  ['getrkidata_1344',['getRKIData',['../namespaceepidemiology_1_1epidata_1_1getRKIData.html',1,'epidemiology::epidata']]],
  ['getrkidatawithestimations_1345',['getRKIDatawithEstimations',['../namespaceepidemiology_1_1epidata_1_1getRKIDatawithEstimations.html',1,'epidemiology::epidata']]],
  ['getsimulationdata_1346',['getSimulationData',['../namespaceepidemiology_1_1epidata_1_1getSimulationData.html',1,'epidemiology::epidata']]],
  ['getvaccinedata_1347',['getVaccineData',['../namespaceepidemiology_1_1epidata_1_1getVaccineData.html',1,'epidemiology::epidata']]],
  ['regions_1348',['regions',['../namespaceepi_1_1regions.html',1,'epi']]]
];
